### ISSUE TITLE
Q-ctrl function returns exact floating point 1.0 values and 0.0 standard deviation in cases

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-catalog#24]
### Steps to reproduce the problem
Consider the circuit and operator pair

```python
qc = QuantumCircuit(6)
op = SparsePauliOp('Z'*6)
```

Running this through the q-ctrl function gives a value of exactly 1.0 and a standard deviation of zero.  Since this is not possible, it looks like bug.
### What is the current behavior?
For testing, it looks like the q-ctrl circuit function maps values outside the domain of [-1, 1] to the boundaries of this allowed region.  It also seems to set the standard deviation to zero in these cases.  I have observed this on several examples outside of the trivial case here as well.

### What is the expected behavior?
Results should be faithful to the implementation and include meaningful error estimates.

**Comment by chongyouquan** [comment]
Hi @nonhermitian, we ran the above circuit through the `StatevectorEstimator`, and got the same results (i.e. it gives an expectation value of exactly 1.0 with a standard deviation of zero):

```
from qiskit.primitives import StatevectorEstimator
from qiskit.quantum_info import SparsePauliOp
from qiskit import QuantumCircuit

qc = QuantumCircuit(6)
op = SparsePauliOp('Z'*6)
pubs = [(qc, op)]

estimator = StatevectorEstimator()

job = estimator.run(pubs)
result = job.result()
print(result[0].data.evs)
```

In this case, since the measurements are in the `Z` basis, there are actually no observables added. That is, the circuit executed is actually empty.

Having a result of an expectation value of exactly 1.0 with a standard deviation of zero only indicates that the 6 IBM qubits used during the circuit execution are all initialized in ground state (as expected), which shows the stability of the IBM device, but does not indicate anything about the Q-CTRL Estimator.

Could you give some non-trivial examples (where the circuit is non-empty), if you've seen this occurring in other instances?

**Comment by nonhermitian** [comment]
I am not sure I follow?  Is Q-ctrl running a statevector simulator internally if the number of qubits is small enough?  Otherwise there are SPAM errors that should cause a distribution to yield an expectation value less than 1.0, and a nonzero standard deviation.  The goal of running such as circuit would be to see if the Q-ctrl (and other) functions can clean it up.

**Comment by chongyouquan** [comment]
Q-CTRL does not run a statevector simulator internally. We compile the circuit and run it on the device always.

I'm saying that:
1. The output of 1.0 is numerically correct.
2. In this case, the circuit is empty. That is, there are no gates, it's just measuring qubits that are in the ground state.

Have you tried larger circuits, where the SPAM errors could be more statistically significant?

**Comment by nonhermitian** [comment]
Here is the distribution executed for a Job that gets reported with a numerically exact result with zer0 standard deviation:

```python

{'000000': 3913,
 '000010': 26,
 '100000': 15,
 '010000': 20,
 '001000': 9,
 '000100': 10,
 '000001': 6,
 '101000': 1}
```

As you can see, the results are not perfect, nor would one expect them to be given the error rates on IBM systems and the number of shots taken.  For the record, the job ID is `cwmhmz3mptp000864geg`

![Image](https://github.com/user-attachments/assets/8c0eb607-62c2-481a-875e-912aae3a2533)

It cannot be readout error mitigation as well because that does not yield numerically exact answers, and the standard deviation gets worse when it is applied.

**Comment by nonhermitian** [comment]
This circuit:

```python

qc = QuantumCircuit(127)
qc.rx(9*1e-4, range(127))
op = SparsePauliOp('Z'*127)
```
sometimes returns exact floating-point values for the expectation and standard deviation, where as other times the result is quite different, e.g .`array([0.2605])` and `array([0.96547385])` for the expval and deviation, respectively

Job id for exact floating point is `cwn12qj543p00086yg80`, other results is `cwn13qe40e000089e6s0`

It seems that close to identical gate values like an id gate or an x-gate one always gets exact floating point values, but get par enough away then is begins to jump around.

**Comment by rowenwu** [comment]
Hi @nonhermitian,
Our readout error mitigation procedure differs from the standard `QiskitRuntime` method, and it could potentially zero out the probabilities of certain bitstrings. In this case, it happened to zero out all bitstrings that were not the target bitstring.
Since the standard deviation is calculated after readout error mitigation is applied, it's possible to have a std dev of 0.

**Comment by nonhermitian** [comment]
Interesting.  Since all error mitigation incurs a cost that manifests itself as an increase in the uncertainty I am not sure how this is possible.  The overhead is exponential in terms of number of measured qubits for readout mitigation, and also depends of course on the device error rates.  It is of course possible to compute a variance on the output distribution that ignores this, but that would be incorrect.  That being said, it would be good to document this for your end users.

**Comment by nonhermitian** [comment]
Closing as this is expected behavior per discussion above.
